dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success: $ travis sshkey --upload ~/.ssh/id_rsa -r myorg/main
Key description: Key to clone myorg/lib1 and myorg/lib2
  updating ssh key for myorg/main with key from ~/.ssh/id_rsa
Current SSH key: Key to clone myorg/lib1 and myorg/lib2